[package]
name = "clipfil"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
copypasta = "0.7.1"
wl-clipboard-rs = "0.8.1"
tempfile = "3.3.0"
